### PR TITLE
ACF-12 # update to @jokeyrhyme/appcache-fetcher@2.0.1

### PR DESCRIPTION
**Pull request by simonmarklar**
- update dependency
- bump version number for npm

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
I tend to bump the package version in the same commit that I update the CHANGELOG.md. And what I put in the change log is what I copy-paste into the GitHub Releases area.

The other thing I've noticed here is the SemVer version range permitted for @jokeyrhyme/appcache-fetcher. My current thinking is:
- always have permissive version ranges for devDependencies e.g. `"^1.2.3"`
- packages that are libraries should also be permissive
  - to avoid having multiple compatible versions of the same dependencies being installed
  - it's also more convenient for us and anyone using the library
- packages that are the deliverables themselves (e.g. HTTP services, CLIs, etc) like this package should be strict e.g. `"1.2.3"`
  - so that it's easier for us to reproduce bug reports, because we'll be installing exactly what the user installed

That said, I haven't investigated `npm shrinkwrap`, and perhaps _that_ is what we should be using to cover the reproducibility angle. /shrug

Also, I've restarted the AppVeyor builds multiple times now and they always fail. Not sure what to do there. Maybe we should just disable AppVeyor?

**Comment by jokeyrhyme** [comment]
As always, this is very much a discussion. I'm not saying you MUST change anything you've done here first. Just that there are a few things we SHOULD consider together.

**Comment by simonmarklar** [comment]
makes sense, I'll make the changes and resubmit

**Comment by jokeyrhyme** [comment]
LGTM 👍 
You cool with tagging, pushing the tags, and publishing to NPM?

**Comment by simonmarklar** [comment]
yeah sure

**Pull request merged**
