### PR TITLE
Update documenation

### PR DESCRIPTION
**Pull request by simonmarklar**

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
LGTM :+1: 
It's worth double-checking this with a customer advocate, and probably also with @maggieshi.

**Comment by maggieshi** [comment]
@simonmarklar Did you double check building the app against both windows 8.1 and windows 10 with the same code base and config xml?

**Comment by simonmarklar** [comment]
I have built and run the same answerspace app using 

```
<preference name="windows-target-version" value="10.0" />
<preference name="windows-target-version" value="8.1" />
```

and by using each target separately.  I've also added android as a platform to the sane project

They all build and run fine. I have not tested the Maps cordova plug in though. I expect that it will have some problems because of the removal of `MSApp.execUnsafeLocalFunction`

However, I checked the AppPackages folder and there is only one installer when both versions are targeted, I would expect an installer for both version targets. 

So then I opened config.xml in visual studio xml designer and the windows version is a singe select drop down. Which seems at odds with the codova docs statement "If you are targeting Windows 10 only, you only need to have a single windows-target-version setting in your config.xml file.". Unless I'm reading that wrong...

I'll modify the document to say that you can target either 8.1 or 10, and remove any references to using both.

**Comment by jokeyrhyme** [comment]
We can ignore the CI failure here.

Everything marked as a peerDependency in npm 2 now needs to explicitly be depended upon by its dependents (i.e. this project) in npm 3.

**Pull request merged**
